name: luas-de-jupyter
channels:
  - conda-forge
dependencies:
  - bqplot=0.12.29
  - ipycanvas=0.8.2
  - ipycytoscape=1.2.2
  - ipydatagrid=1.0.7
  - ipygany=0.5.0
  - ipyleaflet=0.14.0
  - ipympl=0.7.0
  - ipytree=0.2.1
  - ipyvolume=0.6.0a8
  - ipyvuetify=1.7.0
  - ipywidgets=7.6
  - jupyterlab=3
  - numpy
  - pandas
  - pip
  - python=3.8
  - pythreejs=2.3.0
  - pyvista=0.31.3
  - requests
  - scikit-image
  - scipy
  - sidecar=0.5.1
  - voila=0.2.10
  - voila-vuetify=0.5.2
  - voila-material=0.4.0
  - vtk=8.2.0
